// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppLoanTrackerFrequencyTypeEnum string

const (
	AppLoanTrackerFrequencyTypeEnumWEEKLY    AppLoanTrackerFrequencyTypeEnum = "WEEKLY"
	AppLoanTrackerFrequencyTypeEnumBIWEEKLY  AppLoanTrackerFrequencyTypeEnum = "BI_WEEKLY"
	AppLoanTrackerFrequencyTypeEnumMONTHLY   AppLoanTrackerFrequencyTypeEnum = "MONTHLY"
	AppLoanTrackerFrequencyTypeEnumQUARTERLY AppLoanTrackerFrequencyTypeEnum = "QUARTERLY"
	AppLoanTrackerFrequencyTypeEnumYEARLY    AppLoanTrackerFrequencyTypeEnum = "YEARLY"
)

func (e *AppLoanTrackerFrequencyTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppLoanTrackerFrequencyTypeEnum(s)
	case string:
		*e = AppLoanTrackerFrequencyTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AppLoanTrackerFrequencyTypeEnum: %T", src)
	}
	return nil
}

type NullAppLoanTrackerFrequencyTypeEnum struct {
	AppLoanTrackerFrequencyTypeEnum AppLoanTrackerFrequencyTypeEnum
	Valid                           bool // Valid is true if AppLoanTrackerFrequencyTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppLoanTrackerFrequencyTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AppLoanTrackerFrequencyTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppLoanTrackerFrequencyTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppLoanTrackerFrequencyTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppLoanTrackerFrequencyTypeEnum), nil
}

type AppLoanTrackerLoanStatusEnum string

const (
	AppLoanTrackerLoanStatusEnumPENDING   AppLoanTrackerLoanStatusEnum = "PENDING"
	AppLoanTrackerLoanStatusEnumACTIVE    AppLoanTrackerLoanStatusEnum = "ACTIVE"
	AppLoanTrackerLoanStatusEnumPAIDOFF   AppLoanTrackerLoanStatusEnum = "PAID_OFF"
	AppLoanTrackerLoanStatusEnumDEFAULTED AppLoanTrackerLoanStatusEnum = "DEFAULTED"
)

func (e *AppLoanTrackerLoanStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppLoanTrackerLoanStatusEnum(s)
	case string:
		*e = AppLoanTrackerLoanStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AppLoanTrackerLoanStatusEnum: %T", src)
	}
	return nil
}

type NullAppLoanTrackerLoanStatusEnum struct {
	AppLoanTrackerLoanStatusEnum AppLoanTrackerLoanStatusEnum
	Valid                        bool // Valid is true if AppLoanTrackerLoanStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppLoanTrackerLoanStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AppLoanTrackerLoanStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppLoanTrackerLoanStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppLoanTrackerLoanStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppLoanTrackerLoanStatusEnum), nil
}

type AppLoanTrackerLedger struct {
	TransctionID pgtype.UUID
	LoanID       pgtype.UUID
	SenderUserID pgtype.UUID
	Amount       pgtype.Numeric
	LoanVersion  int32
	CreatedAt    pgtype.Timestamptz
	Description  *string
	Metadata     []byte
}

type AppLoanTrackerLoan struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	OriginalPrincipal    pgtype.Numeric
	Principal            pgtype.Numeric
	YearlyInterest       pgtype.Numeric
	InterestCalculatedAt pgtype.Timestamptz
	DueAt                pgtype.Timestamptz
	PaymentFrequency     AppLoanTrackerFrequencyTypeEnum
	NextPaymentAt        pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CurrentVersion       int32
	Status               AppLoanTrackerLoanStatusEnum
	Description          *string
	Metadata             []byte
}

type AppLoanTrackerUserLedgerView struct {
	TransctionID pgtype.UUID
	LoanID       pgtype.UUID
	SenderUserID pgtype.UUID
	Amount       pgtype.Numeric
	LoanVersion  int32
	CreatedAt    pgtype.Timestamptz
	Description  *string
}

type AppLoanTrackerUserLoanView struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	OriginalPrincipal    pgtype.Numeric
	Principal            pgtype.Numeric
	YearlyInterest       pgtype.Numeric
	InterestCalculatedAt pgtype.Timestamptz
	DueAt                pgtype.Timestamptz
	PaymentFrequency     AppLoanTrackerFrequencyTypeEnum
	NextPaymentAt        pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CurrentVersion       int32
	Status               AppLoanTrackerLoanStatusEnum
	Description          *string
}
