// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reads.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserLoanByID = `-- name: GetUserLoanByID :one
SELECT id, user_id, original_principal, principal, yearly_interest, interest_calculated_at, due_at, payment_frequency, next_payment_at, updated_at, current_version, status, description
FROM app_loan_tracker.user_loan_view
WHERE id = $1
  AND user_id = $2
`

type GetUserLoanByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetUserLoanByID(ctx context.Context, arg GetUserLoanByIDParams) (AppLoanTrackerUserLoanView, error) {
	row := q.db.QueryRow(ctx, getUserLoanByID, arg.ID, arg.UserID)
	var i AppLoanTrackerUserLoanView
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalPrincipal,
		&i.Principal,
		&i.YearlyInterest,
		&i.InterestCalculatedAt,
		&i.DueAt,
		&i.PaymentFrequency,
		&i.NextPaymentAt,
		&i.UpdatedAt,
		&i.CurrentVersion,
		&i.Status,
		&i.Description,
	)
	return i, err
}

const getUserLoanLedger = `-- name: GetUserLoanLedger :many
SELECT ledger.transction_id, ledger.loan_id, ledger.sender_user_id, ledger.amount, ledger.loan_version, ledger.created_at, ledger.description
FROM app_loan_tracker.user_ledger_view AS ledger
  JOIN app_loan_tracker.user_loan_view ON id = ledger.id
WHERE loan_id = $1
  AND user_id = $2
`

type GetUserLoanLedgerParams struct {
	LoanID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetUserLoanLedger(ctx context.Context, arg GetUserLoanLedgerParams) ([]AppLoanTrackerUserLedgerView, error) {
	rows, err := q.db.Query(ctx, getUserLoanLedger, arg.LoanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppLoanTrackerUserLedgerView
	for rows.Next() {
		var i AppLoanTrackerUserLedgerView
		if err := rows.Scan(
			&i.TransctionID,
			&i.LoanID,
			&i.SenderUserID,
			&i.Amount,
			&i.LoanVersion,
			&i.CreatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLoans = `-- name: GetUserLoans :many
SELECT id, user_id, original_principal, principal, yearly_interest, interest_calculated_at, due_at, payment_frequency, next_payment_at, updated_at, current_version, status, description
FROM app_loan_tracker.user_loan_view
WHERE user_id = $1
`

func (q *Queries) GetUserLoans(ctx context.Context, userID pgtype.UUID) ([]AppLoanTrackerUserLoanView, error) {
	rows, err := q.db.Query(ctx, getUserLoans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppLoanTrackerUserLoanView
	for rows.Next() {
		var i AppLoanTrackerUserLoanView
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalPrincipal,
			&i.Principal,
			&i.YearlyInterest,
			&i.InterestCalculatedAt,
			&i.DueAt,
			&i.PaymentFrequency,
			&i.NextPaymentAt,
			&i.UpdatedAt,
			&i.CurrentVersion,
			&i.Status,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
