services:
  dev:
    container_name: loanTracker-dev
    build:
      context: ..
      dockerfile: ./loan-tracker/Dockerfile
      target: dev 
    network_mode: host
    volumes:
      - .:/app
      - ../auth.hetlesaether.com:/auth.hetlesaether.com
      - /tmp/loanTracker/srv

