// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: pkg/auth/proto/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionToken    string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Appliaction     string                 `protobuf:"bytes,2,opt,name=appliaction,proto3" json:"appliaction,omitempty"`
	AuthorizedRoles []string               `protobuf:"bytes,3,rep,name=authorized_roles,json=authorizedRoles,proto3" json:"authorized_roles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_pkg_auth_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_auth_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *SessionRequest) GetAppliaction() string {
	if x != nil {
		return x.Appliaction
	}
	return ""
}

func (x *SessionRequest) GetAuthorizedRoles() []string {
	if x != nil {
		return x.AuthorizedRoles
	}
	return nil
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_pkg_auth_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_auth_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_pkg_auth_proto_auth_proto protoreflect.FileDescriptor

const file_pkg_auth_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/auth/proto/auth.proto\x12\x04auth\"\x82\x01\n" +
	"\x0eSessionRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12 \n" +
	"\vappliaction\x18\x02 \x01(\tR\vappliaction\x12)\n" +
	"\x10authorized_roles\x18\x03 \x03(\tR\x0fauthorizedRoles\"*\n" +
	"\x0fSessionResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2M\n" +
	"\vAuthService\x12>\n" +
	"\x0fValidateSession\x12\x14.auth.SessionRequest\x1a\x15.auth.SessionResponseB-Z+hetlesaether.com/auth/pkg/auth/proto;authpbb\x06proto3"

var (
	file_pkg_auth_proto_auth_proto_rawDescOnce sync.Once
	file_pkg_auth_proto_auth_proto_rawDescData []byte
)

func file_pkg_auth_proto_auth_proto_rawDescGZIP() []byte {
	file_pkg_auth_proto_auth_proto_rawDescOnce.Do(func() {
		file_pkg_auth_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_auth_proto_rawDesc), len(file_pkg_auth_proto_auth_proto_rawDesc)))
	})
	return file_pkg_auth_proto_auth_proto_rawDescData
}

var file_pkg_auth_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_auth_proto_auth_proto_goTypes = []any{
	(*SessionRequest)(nil),  // 0: auth.SessionRequest
	(*SessionResponse)(nil), // 1: auth.SessionResponse
}
var file_pkg_auth_proto_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.ValidateSession:input_type -> auth.SessionRequest
	1, // 1: auth.AuthService.ValidateSession:output_type -> auth.SessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_auth_proto_auth_proto_init() }
func file_pkg_auth_proto_auth_proto_init() {
	if File_pkg_auth_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_proto_auth_proto_rawDesc), len(file_pkg_auth_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_auth_proto_auth_proto_goTypes,
		DependencyIndexes: file_pkg_auth_proto_auth_proto_depIdxs,
		MessageInfos:      file_pkg_auth_proto_auth_proto_msgTypes,
	}.Build()
	File_pkg_auth_proto_auth_proto = out.File
	file_pkg_auth_proto_auth_proto_goTypes = nil
	file_pkg_auth_proto_auth_proto_depIdxs = nil
}
